### PR TITLE
Added facet_grid() and facet_wrap() support

### PR DESCRIPTION
**Pull request by cyrusae**
- Added definitions for `facet_wrap()` and `facet_grid()`
- Added optional `data` parameter (imitating ggplot) in order to parse variable names 
- Added vignette for faceting

### CODE REVIEW

**Comment by brandmaier** [comment]
This is a fantastic addition! Thanks so much!

**Comment by brandmaier** [comment]
If you don't mind, I would like to add you as contributor to the package. Let me know under what full name (and potentially email address) you would like to take credit.

**Comment by cyrusae** [comment]
> If you don't mind, I would like to add you as contributor to the package. Let me know under what full name (and potentially email address) you would like to take credit.

Thank you so much! My name is Cyrus Eosphoros, I am not great at keeping up with email but if you think it's worth adding anyway my address is `cyrus.eosphoros` [at] `gmail`. (:

**Comment by cyrusae** [comment]
Addendum: saw that there was a subsequent bug fix in the faceting code I didn't have covered, thank you/apologies for not catching it myself!

**Comment by brandmaier** [comment]
OK, you are listed as contributor as of 47885c1a69aba4a7c6ad0258cd3fd0a46404cd91

**Pull request merged**
